baseURL = "https://blog.mulbx.top/"
# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"
# 网站语言, 仅在这里 CN 大写
languageCode = "zh-CN"
# 是否包括中日韩文字
title = "Unnoted Melody"

hasCJKLanguage = true
# 网站标题
# 更改使用 Hugo 构建网站时使用的默认主题
theme = "DoIt"

# 网站关键词
keywords = [
  "Mulberror",
  "blog",
  "森绪",
  "莫柏瑞",
  "full-stack",
  "computer science",
  "mathematics",
  "Unnoted Melody"
]

# DoIt 新增 | 0.2.0 日期格式
dateFormat = "2006-01-02"
