weight = 1
# language code, CN only here
languageCode = "zh-CN"
languageName = "简体中文"
# whether to include Chinese/Japanese/Korean
hasCJKLanguage = true

[params.author]
name = "森绪"

# 中文标题
[params.header.title]
# 标题名
name = """
<svg class="icon" viewBox="0 0 576 512"><path d="M402.3 344.9l32-32c5-5 13.7-1.5 13.7 5.7V464c0 26.5-21.5 48-48 48H48c-26.5.0-48-21.5-48-48V112c0-26.5 21.5-48 48-48h273.5c7.1.0 10.7 8.6 5.7 13.7l-32 32c-1.5 1.5-3.5 2.3-5.7 2.3H48v352h352V350.5c0-2.1.8-4.1 2.3-5.6zm156.6-201.8L296.3 405.7l-90.4 10c-26.2 2.9-48.5-19.2-45.6-45.6l10-90.4L432.9 17.1c22.9-22.9 59.9-22.9 82.7.0l43.2 43.2c22.9 22.9 22.9 60 .1 82.8zM460.1 174 402 115.9 216.2 301.8l-7.3 65.3 65.3-7.3L460.1 174zm64.8-79.7-43.2-43.2c-4.1-4.1-10.8-4.1-14.8.0L436 82l58.1 58.1 30.9-30.9c4-4.2 4-10.8-.1-14.9z"></path></svg>
未定的旋律
"""

# DoIt 新增 | 0.2.13 赞赏配置
[params.sponsor]
enable = true
bio = "如果觉得我的文章有帮助，欢迎赠我一杯免费的咖啡~"
link = "" # 你的赞赏页面的地址
custom = "" # 自定义 HTML

[params.home.profile]
enable = true
# Gravatar 邮箱，用于优先在主页显示的头像
# gravatarEmail = "mulberror@gmail.com"
# 头像的链接指向的 URL
avatarLinkURL = "https://blog.mulbx.top/"
# DoIt 更改 | 0.2.7 主页显示的网站标题 (支持 HTML 格式)
title = ""
# 主页显示的网站副标题
subtitle = "与其抱怨长夜，何不秉烛夜行。"
# 是否为副标题显示打字机动画
typeit = true
# 是否显示社交账号
social = true
# DoIt 新增 | 0.2.0 免责声明 (支持 HTML 格式)
disclaimer = ""

[params.home.posts]
enable = true
# special amount of posts in each home posts page
paginate = 10

# DoIt 更改 | 0.2.7 第三方库文件的 CDN 设置
# [params.cdn]
#   # CDN 数据文件名称, 默认不启用
#   # 位于 "themes/DoIt/assets/data/cdn/" 目录
#   # 可以在你的项目下相同路径存放你自己的数据文件:
#   # "assets/data/cdn/"
#   data = "jsdelivr.yml"

[[menu.main]]
identifier = "homapage"
pre = ""
post = ""
name = "首页"
url = "/"
title = ""
weight = 1

[[menu.main]]
identifier = "series"
pre = ""
post = ""
name = "系列"
url = "/series/"
title = ""
weight = 3

[[menu.main]]
identifier = "categories"
pre = ""
post = ""
name = "分类"
url = "/categories/"
title = ""
weight = 5

[[menu.main]]
identifier = "tags"
pre = ""
post = ""
name = "标签"
url = "/tags/"
title = ""
weight = 7

[[menu.main]]
identifier = "about"
pre = ""
post = ""
name = "关于"
url = "/about/"
title = ""
weight = 9
