# Hugo 解析文档的配置
# 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
[highlight]
# false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
noClasses = false

[goldmark]
[goldmark.extensions]
[goldmark.extensions.passthrough]
enable = true
[goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]']]
inline = [['\(', '\)']]
