
[[main]]
identifier = "homepage"
pre = """<i class="fa-solid fa-house"></i>"""
post = ""
name = "Home"
url = "/"
title = ""
weight = 1

[[main]]
identifier = "documentation"
pre = """<i class="fa-solid fa-feather"></i>"""
name = "Archives"
url = "/posts/"
title = ""
weight = 2

[[main]]
identifier = "collections"
pre = """<i class="fa-solid fa-layer-group"></i>"""
post = ""
name = "Collections"
url = "/collections/"
title = ""
weight = 3

[[main]]
identifier = "categories"
pre = """<i class="fa-solid fa-folder-tree"></i>"""
post = ""
name = "Category"
url = "/categories/"
title = ""
weight = 5

[[main]]
identifier = "Tags"
pre = """<i class="fa-solid fa-tags"></i>"""
post = ""
name = "Tags"
url = "/tags/"
title = ""
weight = 7

[[main]]
identifier = "friends"
pre = """<i class="fa-solid fa-user-group"></i>"""
post = ""
name = "Friends"
url = "/friends"
title = ""
weight = 8

[[main]]
identifier = "About"
pre = """<i class="fa-solid fa-droplet"></i>"""
post = ""
name = "About"
url = "/about/"
title = ""
weight = 9
