# -------------------------------------------------------------------------------------
# Menu Configuration | 菜单配置
# See: https://fixit.lruihao.cn/zh-cn/documentation/basics/#menu-configuration
# -------------------------------------------------------------------------------------

[[main]]
identifier = "homapage"
pre = """<i class="fa-solid fa-house"></i>"""
post = ""
name = "首页"
url = "/"
title = ""
weight = 1

[[main]]
identifier = "collections"
parent = "archives"
name = "合集"
url = "/collections/"
weight = 3
[main.params]
icon = "fa-solid fa-layer-group"

[[main]]
identifier = "categories"
parent = "archives"
pre = """<i class="fa-solid fa-folder-tree"></i>"""
post = ""
name = "分类"
url = "/categories/"
title = ""
weight = 5

[[main]]
identifier = "tags"
parent = "archives"
pre = """<i class="fa-solid fa-tags"></i>"""
post = ""
name = "标签"
url = "/tags/"
title = ""
weight = 7

[[main]]
identifier = "archives"
pre = """<i class="fa-solid fa-box-archive"></i>"""
name = "归档"
url = "archives/"
title = ""
weight = 2

[[main]]
identifier = "friends"
pre = """<i class="fa-solid fa-user-group"></i>"""
post = ""
name = "友链"
url = "/friends"
title = ""
weight = 8

[[main]]
identifier = "about"
pre = """<i class="fa-solid fa-droplet"></i>"""
post = ""
name = "关于"
url = "/about/"
title = ""
weight = 9
