
[[main]]
identifier = "homapage"
pre = """<i class="fa-solid fa-house"></i>"""
post = ""
name = "首页"
url = "/"
title = ""
weight = 1

[[main]]
identifier = "documentation"
pre = """<i class="fa-solid fa-feather"></i>"""
name = "归档"
url = "/posts/"
title = ""
weight = 2

[[main]]
identifier = "collections"
pre = """<i class="fa-solid fa-layer-group"></i>"""
post = ""
name = "合集"
url = "/collections/"
title = ""
weight = 3

[[main]]
identifier = "categories"
pre = """<i class="fa-solid fa-folder-tree"></i>"""
post = ""
name = "分类"
url = "/categories/"
title = ""
weight = 5

[[main]]
identifier = "tags"
pre = """<i class="fa-solid fa-tags"></i>"""
post = ""
name = "标签"
url = "/tags/"
title = ""
weight = 7

[[main]]
identifier = "friends"
pre = """<i class="fa-solid fa-user-group"></i>"""
post = ""
name = "友链"
url = "/friends"
title = ""
weight = 8

[[main]]
identifier = "about"
pre = """<i class="fa-solid fa-droplet"></i>"""
post = ""
name = "关于"
url = "/about/"
title = ""
weight = 9
