
[[main]]
identifier = "homepage"
pre = """<i class="fa-solid fa-house"></i>"""
post = ""
name = "Home"
url = "/"
title = ""
weight = 10

[[main]]
identifier = "archives"
pre = """<i class="fa-solid fa-feather"></i>"""
name = "Archives"
url = "/archives/"
title = ""
weight = 20

[[main]]
identifier = "collections"
parent = "archives"
pre = """<i class="fa-solid fa-layer-group"></i>"""
post = ""
name = "Collections"
url = "/collections/"
title = ""
weight = 30

[[main]]
identifier = "categories"
parent = "archives"
pre = """<i class="fa-solid fa-folder-tree"></i>"""
post = ""
name = "Category"
url = "/categories/"
title = ""
weight = 50

[[main]]
identifier = "Tags"
parent = "archives"
pre = """<i class="fa-solid fa-tags"></i>"""
post = ""
name = "Tags"
url = "/tags/"
title = ""
weight = 70

[[main]]
identifier = "links"
pre = """<i class="fa-solid fa-link"></i>"""
post = ""
name = "Links"
url = ""
title = ""
weight = 75

[[main]]
identifier = "friends"
pre = """<i class="fa-solid fa-paper-plane"></i>"""
parent = "links"
post = ""
name = "Friends"
url = "/friends"
title = ""
weight = 80

[[main]]
identifier = "note"
pre = """<i class="fa-solid fa-pen-to-square"></i>"""
parent = "links"
post = ""
name = "Notebook"
url = "https://note.mulbx.top"
title = ""
weight = 81

[[main]]
identifier = "About"
pre = """<i class="fa-solid fa-droplet"></i>"""
post = ""
name = "About"
url = "/about/"
title = ""
weight = 100
