# FixIt 更改 | 0.2.0
# 为了支持搜索，需要在这里设定，输出 json 索引文件
# <domain>/atom.xml
_merge = "shallow"
home = ["html", "rss", "archives", "offline", "search"]
page = ["html", "markdown"]
section = ["html", "rss"]
taxonomy = ["html"]
term = ["html", "rss"]
