

[search]
enable = true
# type of search engine ("algolia", "fuse")
# 搜索引擎的类型 ("algolia", "fuse")
type = "algolia"
# max index length of the chunked content
# 文章内容最长索引长度
contentLength = 4000
# placeholder of the search bar
# 搜索框的占位提示语
placeholder = ""
# max number of results length
# 最大结果数目
maxResultLength = 10
# snippet length of the result
# 结果内容片段长度
snippetLength = 50
# HTML tag name of the highlight part in results
# 搜索结果中高亮部分的 HTML 标签
highlightTag = "em"
# whether to use the absolute URL based on the baseURL in search index
# 是否在搜索索引中使用基于 baseURL 的绝对路径
absoluteURL = false
[search.algolia]
index = "en_index"
appID = "MXP1WFVWGE"
searchKey = "e718147816b4e89d6799cf290fa03961"
