# Permalinks config (https://gohugo.io/content-management/urls/#permalinks)
# Permalinks 配置 (https://gohugo.io/content-management/urls/#permalinks)

# posts = ":year/:month/:filename"
# posts = ":filename"
documentation = ":sections[0:]/:slugorfilename"
guides = "guides/:slugorfilename"
