baseURL: "https://blog.mulberror.top" # 
title: Mulberror's Blog
copyright: "[©2023 Mulberror's Blog](https://blog.mulberror.top)" # 网站的版权声明，通常显示在页脚
paginate: 15
theme: PaperMod
languageCode: zh-cn

enableInlineShortcodes: true # shortcode，类似于模板变量，可以在写 markdown 的时候便捷地插入，官方文档中有一个视频讲的很通俗
enableRobotsTXT: true # 允许生成 robots.txt
buildDrafts: false # 构建时是否包括草稿
buildFuture: false # 构建未来发布的内容
buildExpired: false # 构建过期的内容

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: English
    languageCode: en
    contentDir: content/English
    
params:
  math: true
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: ExampleSite
  description: "ExampleSite description"
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "2006-01-02"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowWordCounts: true
  ShowLastMod: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/img/favicon.png"
    favicon16x16: "/img/favicon.png"
    favicon32x32: "/img/favicon.png"
    apple_touch_icon: "/img/favicon.png"
    safari_pinned_tab: "/img/favicon.png"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]
    includeMatches: true

defaultContentLanguage: zh
defaultContentLanguageInSubdir: true

languages:
  zh:
    languageName: 中文
    languageCode: zh
    contentDir: content/Chinese
    menu:
      main:
        - identifier: home
          name: 首页
          url: /
          weight: 10
        - identifier: search
          name: 搜索
          url: /search
          weight: 20
        - identifier: archives
          name: 归档
          url: /archives
          weight: 30
        - identifier: tags
          name: 标签
          url: tags
          weight: 40
        - identifier: links
          name: 友链
          url: /links
          weight: 45
  # profile-mode
    params:
      label:
        text: "桑葚的博客"
        icon: /apple-touch-icon.png
        iconHeight: 35
      profileMode:
        enabled: false # needs to be explicitly set
        title: mulberror's blog
        subtitle: "This is subtitle"
        imageUrl: "img/avatar.png"
        imageWidth: 120
        imageHeight: 120
        imageTitle: avatar
        buttons:
        # - name: Posts
        #   url: posts
        # - name: Tags
        #   url: tags

      # home-info mode
      homeInfoParams:
        Title: "桑葚的后花园"
        Content: 欢迎来到我的博客，这里记录着一些微不足道的文章。

      socialIcons:
        - name: email
          url: "mailto:mulberror@gmail.com"
        - name: github
          url: "https://github.com/mulberror"
        - name: WeChat
          url: "../img/wechat.jpg"
        - name: QQ
          url: "../img/qq.png"
        - name: bilibili
          url: "https://space.bilibili.com/228169364"
        - name: RSS
          url: "index.xml"
      
  en:
    languageName: English
    languageCode: en
    contentDir: content/English
    params:
      label:
        text: "Mulberror's Blog"
        icon: /apple-touch-icon.png
        iconHeight: 35
      profileMode:
        enabled: true # needs to be explicitly set
        title: Mulberror's Blog
        subtitle: "Hi, here's Mulberror Zhang."
        imageUrl: "img/avatar.png"
        imageWidth: 120
        imageHeight: 120
        imageTitle: avatar
        buttons:

StartYear: 2023
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    # lineNos: true
    style: monokai
    # codeFences：代码围栏功能，这个功能一般都要设为 true 的，不然很难看，就是干巴巴的-代码文字，没有颜色。
    # guessSyntax：猜测语法，这个功能建议设置为 true, 如果你没有设置要显示的语言则会自动匹配。
    # hl_Lines：高亮的行号，一般这个不设置，因为每个代码块我们可能希望让高亮的地方不一样。
    # lineNoStart：行号从编号几开始，一般从 1 开始。
    # lineNos：是否显示行号，我比较喜欢显示，所以我设置的为 true.
    # lineNumbersInTable：使用表来格式化行号和代码,而不是 标签。这个属性一般设置为 true.
    # noClasses：使用 class 标签，而不是内嵌的内联样式

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
